apiVersion: v1
kind: List
items:
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    labels:
      project: "zipkin"
      provider: "fabric8"
    name: "zipkin"
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: "zipkin"
        provider: "fabric8"
    template:
      metadata:
        labels:
          project: "zipkin"
          provider: "fabric8"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "openzipkin/zipkin:1.13"
          imagePullPolicy: "IfNotPresent"
          name: "zipkin"
          ports:
          - containerPort: 9411
          - containerPort: 9410
- apiVersion: v1
  kind: "Service"
  metadata:
    labels:
      project: "zipkin"
      provider: "fabric8"
    name: "zipkin"
  spec:
    ports:
    - port: 80
      name: "zipkin-web"
      protocol: "TCP"
      targetPort: 9411
    - port: 9140
      name: "zipkin-data"
      protocol: "TCP"
      targetPort: 9410
    selector:
      project: "zipkin"
      provider: "fabric8"
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: zipkin-web
    namespace: myproject
    labels:
      project: zipkin
      provider: fabric8
  spec:
    host: zipkin-web-myproject.192.168.64.3.nip.io
    to:
      kind: Service
      name: zipkin
    port:
      targetPort: zipkin-web
- apiVersion: v1
  kind: Route
  metadata:
    name: zipkin-data
    namespace: myproject
    labels:
      project: zipkin
      provider: fabric8
  spec:
    host: zipkin-data-myproject.192.168.64.3.nip.io
    to:
      kind: Service
      name: zipkin      
    port:
      targetPort: zipkin-data
